### PR TITLE
Declare my_gethrtime static; fixes build.

### PR DESCRIPTION
**Pull request by wca**
This change was required to build on my laptop running Ubuntu 16.04.1 (gcc 5.4.0), otherwise I get this:

> jtest.o: In function `jopenw':
> /home/will/git/gh/omniti-labs/jlog/jtest.c:229: undefined reference to `my_gethrtime'
> /home/will/git/gh/omniti-labs/jlog/jtest.c:245: undefined reference to `my_gethrtime'

### CODE REVIEW

**Comment by fsaintjacques** [comment]
Bizarrely, on mine (16.04.1 gcc 5.4.0) it borks because

```
jtest.c: In function ‘addonefile’:
jtest.c:175:5: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
     (void)write(fd, &streeng[7*idx], 7);
     ^
jtest.c: In function ‘corruptmetastore’:
jtest.c:190:3: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
   (void)write(fd, &streeng[0], 7);
   ^
```

**Comment by fsaintjacques** [comment]
Fix is:

```
diff --git a/jtest.c b/jtest.c
index 91ac954..f417008 100644
--- a/jtest.c
+++ b/jtest.c
@@ -172,7 +172,7 @@ static void addonefile(const char *logname, const char *nam, int idx) {
   (void)snprintf(ag, leen-1, "%s%c%s", logname, IFS_CH, nam);
   int fd = creat(ag, DEFAULT_FILE_MODE);
   if ( fd >= 0 ) {
-    (void)write(fd, &streeng[7*idx], 7);
+    if (write(fd, &streeng[7*idx], 7) != 7) exit(1);
     (void)close(fd);
   }
   free((void *)ag);
@@ -187,7 +187,7 @@ static void corruptmetastore(const char *logname) {
   int fd = open(ag, 02);
   if ( fd < 0 )
     return;
-  (void)write(fd, &streeng[0], 7);
+  if (write(fd, &streeng[0], 7) != 7) exit(1);
   (void)close(fd);
 }
```

**Comment by postwait** [comment]
This was integrated a long time ago.
